### ISSUE TITLE
Loopback is not working.

### ISSUE THREAD

**Issue by mrrsa** [k8stooling/kubazulo#10]
I tried to use kubazulo to login to kubernetes but when looping back and redirecting to localhost:58433 there isn't a listener that resolves and creates the azuredata.json file

**Comment by maikbrauer** [comment]
@mrrsa 

- Did you check if this port is probably in use by any other process?
- Which Release did you try on which OS-Type?
- Do you get any error Message?
- Did you check the LogFile in `~/.kube/kubazulo/application.log`? Any specific errors?
- What is happening when you use the command without the kubectl ExecPlugin? You can use the binary also directly?

Can you please elaborate more on the points above to get a better picture, what's going on in your case? Thanks a lot.

**Comment by mrrsa** [comment]
**Did you check if this port is probably in use by any other process?** Is not being used by any other  process. i checked on resource monitor
**Which Release did you try on which OS-Type?**kubazulo version 1.0.1
go-runtime: go1.22.3 
**Do you get any error Message?** ERR_CONNECTION_REFUSED
**Did you check the LogFile in ~/.kube/kubazulo/application.log? Any specific errors?**INFO: 2024/07/09 18:07:38 get-token.go:132: Application invoked.
INFO: 2024/07/09 18:07:38 get-token.go:171: Cache File does not exist. New AccessToken obtained from Azure-API via Interactive Flow Loginmode.
**What is happening when you use the command without the kubectl ExecPlugin? You can use the binary also directly?** when i try to run kubectl version it opens the webpage with ERR_CONNECTION_REFUSED. When i run kubazulo just with client and tenant it goes to the webpage and trigger the same error as described above: ERR_CONNECTION_REFUSED

**Comment by maikbrauer** [comment]
Which OS-Type do you use? Windows, MacOS, Linux. And also which Version of those OS do you use?

**Comment by mrrsa** [comment]
Windows 10. My first try was using wsl but then i changed to windows itself and i have the same behaviour in both of them.

**Comment by maikbrauer** [comment]
I tried to reproduce in Windows 10 and Windows 11. All works as designed. Listener is up in both OS-Version and waiting to serve the traffic coming via the redirect to localhost. Might be something specific on your box.

Did you try to influence the Port to a different one, with help of:
` -l, --loopbackport string         Customize local callback listener (default "58433")`

Also please check proxy settings for your browser to exclude `localhost` not to be proxied.

Please try to Authenticate in a `Private session` and then stop put login and password inside. When you see that page, go back to the terminal and check with `netstat -a` if the LISTENER with the port you defined is up.
(!) Please make sure that the comand is pending and waiting for input, otherwise the localserver will be disposed.

**Comment by mrrsa** [comment]
Ok i tried changing the port to 58888 and it worked properly. Thank you for your patience. Best of Luck

**Comment by maikbrauer** [comment]
OK glad to hear, seems that you have something running on this specific port, however. Please let us know in case you have further queries on this. Thanks. We will close the issue for now.
